### ISSUE TITLE
ComfyUI 'widgetInputs.js ' Errors when loading Task_Solving_with_Code_Generation.json

### ISSUE THREAD

**Issue by signalprime** [xXAdonesXx/NodeGPT#11]
Really cool project idea, NodeGPT! 

I followed the installation instructions with a fresh and current install on MacOS for everything listed.  However, when trying to load `Task_Solving_with_Code_Generation.json` within ComfyUI there are errors such as

```
TypeError: undefined is not an object (evaluating 'this.widgets_values.length')
onAfterGraphConfigured@http://127.0.0.1:8188/extensions/core/widgetInputs.js:322:46
@http://127.0.0.1:8188/scripts/app.js:1221:34
@http://127.0.0.1:8188/lib/litegraph.core.js:2260:20
@http://127.0.0.1:8188/scripts/app.js:1201:27
loadGraphData@http://127.0.0.1:8188/scripts/app.js:1451:24
@http://127.0.0.1:8188/scripts/app.js:1298:23
This may be due to the following script:
/extensions/core/widgetInputs.js
```

Any thoughts what is needed to solve it?

Thanks!

**Comment by xXAdonesXx** [comment]
Can you add Autogen nodes manually? Sorry if it doesn't work yet for you. It's in a really early stage.

**Comment by xXAdonesXx** [comment]
Maybe try to download the folder manually and paste it into the custom nodes folder. If I were in your place, I would wait a bit until the nodes are more complete.

**Comment by signalprime** [comment]
Thanks for your suggestions!  It was an environment issue, missing the autogen package inside the newly installed textgen conda environment.  Now back to testing this sweet project out.  Thanks again!
