### ISSUE TITLE
Load API key from config file to avoid workflow contamination

### ISSUE THREAD

**Issue by oddomatik** [xXAdonesXx/NodeGPT#18]
https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92 does this if examples are needed.

Happy to work on a PR at some point if no one gets to it in the next few weeks.

**Comment by xXAdonesXx** [comment]
![grafik](https://github.com/xXAdonesXx/NodeGPT/assets/66518617/c043feeb-817e-49f7-9c4e-1a4439a9d8ab)
I have added your idea. I have not tested it yet

**Comment by xXAdonesXx** [comment]
you can leave the API_Key (if the txt is named OpenAI.txt inside the API_Config folder) empty or use the new node. Both should work
