### ISSUE TITLE
Small bug in Output2String.py

### ISSUE THREAD

**Issue by morteng** [xXAdonesXx/NodeGPT#19]
It only returns the first letter of the generated prompt, I'm no coder but changing the return to

return(text,);

seems to work for me :)

**Comment by alessandroperilli** [comment]
@morteng That's what was the problem. I though the integration with LM Studio was not working and I was going crazy. Thank you. Your workaround works just fine.

@xXAdonesXx: Your work is much appreciated, and I'd like to include your nodes in the upcoming release of [AP Workflow 6.0](https://perilli.com/ai/comfyui/). 

Do you have an ETA for this fix? Thanks!

**Comment by morteng** [comment]
@alessandroperilli Glad to hear it! And I see you noticed the issue with caching as well, I agree with your take on how it should work. Really excited to see NodeGPT in AP Workflow, great work being done by both you and @xXAdonesXx - my thanks and admiration!

**Comment by xXAdonesXx** [comment]
The bug is now fixed, and the workflow should be operating smoothly. Thanks for your patience and kind words!
