### ISSUE TITLE
DisplayText node seems to output to stdout via print() rather than displaying text within ComfyUI

### ISSUE THREAD

**Issue by daniel-lewis-ab** [xXAdonesXx/NodeGPT#33]
Issue:

When configuring nodes as such:

![image](https://github.com/xXAdonesXx/NodeGPT/assets/12051895/f3dfdbbf-36a2-4081-ae6f-45e3f0cbd2e5)

The DisplayText node uses the print() function, which is printing to stdout on my machine and probably most other peoples.

Desired Behavior:

For it to display it to the node contents, preferably in a multiline text widget.

Solution:

Not yet 100% sure, but I can tell the problem likely lies in this usage in DisplayText.py

![image](https://github.com/xXAdonesXx/NodeGPT/assets/12051895/d708a902-f064-47fd-aa69-2e6bbe2397d8)

I'll update in the below comments if I come up with the necessary code.

**Comment by jmanhype** [comment]
Error occurred when executing TextGeneration:

(Deprecated) The autogen.Completion class requires openai<1 and diskcache.

File "/home/straughter/ComfyUI/execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/straughter/ComfyUI/execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/straughter/ComfyUI/execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/straughter/ComfyUI/custom_nodes/NodeGPT/TextGeneration.py", line 45, in execute
response = oai.ChatCompletion.create(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/straughter/.pyenv/versions/3.11.6/lib/python3.11/site-packages/autogen/oai/completion.py", line 792, in create
raise ERROR
